//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Info_Molinetes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZWJvmSpahNsPDvTNi2A77Le9CP+gBBkT1854esO1BA511z1xNAqDta5zOkEqpne485ugAVcGVvVsotuSm" +
            "m5NZobBDOobbQYGy0wdAbHR+Lfa+ZUG3s2VSE5Cann1/crddcnYP9FQr7PlwgIQd0J1pQ==")]
        public string DB_Molinetes {
            get {
                return ((string)(this["DB_Molinetes"]));
            }
            set {
                this["DB_Molinetes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yk5PfJfZjABUwrFs8TCjI2duQ9Q+nBY3T3NowblfVSgNIAuEysxcQlxYwtYWSdEp4qTJp6gOUqrigh3DA" +
            "7z/rg==")]
        public string DB_RRHH {
            get {
                return ((string)(this["DB_RRHH"]));
            }
            set {
                this["DB_RRHH"] = value;
            }
        }
    }
}
